project:
  type: website
  output-dir: docs

website:
  title: "Zimu DENG(Mark) - MUSA 5080 Portfolio"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: "Weekly Notes"
        menu: 
          - href: weekly-notes/week-01-notes.qmd
            text: "Week 1"
          - href: weekly-notes/week-02-notes.qmd
            text: "Week 2"
          - href: weekly-notes/week-03-notes.qmd
            text: "Week 3"
          - href: weekly-notes/week-04-notes.qmd
            text: "Week 4" 
          - href: weekly-notes/week-05-notes.qmd
            text: "Week 5"
          - href: weekly-notes/week-06-notes.qmd
            text: "Week 6" 
          - href: weekly-notes/week-07-notes.qmd
            text: "Week 7"
          - href: weekly-notes/week-08-notes.qmd
            text: "Week 8"
          - href: weekly-notes/week-09-notes.qmd
            text: "Week 9"
          - href: weekly-notes/week-10-notes.qmd
            text: "Week 10"
      - text: "Assignment"
        menu:
          - href: assignments/assignment_1/assignment1.qmd
            text: "Assignment 1: Census Data Exploration"
          - href: assignments/assignment_2/assignment2.qmd
            text: "Assignment 2: Spatial Analysis and Visualization"
          - href: assignments/assignment_3/Cao_Deng_Luu_Rigsby_Stauffer_Vu_Slides.qmd
            text: "Assignment 3: Presentation Slides"
          - href: assignments/assignment_3/Cao_Deng_Luu_Rigsby_Stauffer_Vu_Appendix.qmd
            text: "Assignment 3: Technical_Appendix"
          - href: assignments/assignment_4/assignment4.qmd
            text: "Assignment 4: Spatial Predictive Analysis"
format:
  html:
    theme: cosmo 
    toc: true
    code-fold: show
execute:
  freeze: auto
